
data_root: data/chair_model/test_set # test set with novel views
logging_root: data/chair_model/logs
checkpoint: data/chair_model/checkpoint
num_instances: 4612 # this is used for latent code
batch_size: 4 # This is for a GPU with 48 GB of memory. Adapt accordingly for your GPU memory.
